sudo: true
language: node_js
node_js:
  - '10'

branches:
  only:
    - /.*/

install:
  - yarn install --production=false

script:
  - yarn lint
  - yarn test

notifications:
  email:
    on_failure: always
